version: '3'

# networks:
#   default:
#     external:
#       name: cumulus-api_default
      
services:
  ldm:
    build:
      context: .
    image: ldm-docker:6.13.13
    container_name: ldm
    # restart: always
    environment:
    #   - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
    #   - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    #   - AWS_DEFAULT_REGION=us-east-1
    #   - AWS_S3_ENDPOINT=http://minio:9000
    #   - CUMULUS_HOST_DEVELOP=http://cumulus-api_api_1
    #   - CUMULUS_HOST_STABLE=http://cumulus-api_api_1
    #   - APPLICATION_KEY=appkey
    # volumes:
    #   # change defaults to your liking
    #   - ./cron/:/var/spool/cron/
    #   - ./data/:/home/ldm/var/data/
    #   - ./etc/:/home/ldm/etc/
    #   - ./logs/:/home/ldm/var/logs/
    #   - ./queues/:/home/ldm/var/queues/
    #   - ./data/:/data/
    #   - ./bin/:/home/ldm/local/bin/
    ports:
      - "388:388"
    ulimits:
      nofile:
        soft: 1024
        hard: 1024
    env_file: 
      - compose.env
  # minio:
  #   image: minio/minio
  #   environment:
  #     - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
  #     - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  #   command: server /data
  #   ports:
  #     - "9000:9000"
  # # configure minio on startup (create buckets, etc)
  # # inspired by https://github.com/minio/minio/issues/4769
  # # and         https://gist.github.com/haxoza/22afe7cc4a9da7e8bdc09aad393a99cc    
  # minio_init:
  #   image: minio/mc
  #   depends_on:
  #     - minio
  #   entrypoint: >
  #     /bin/sh -c "
  #     echo 'sleeping for 10 seconds while minio starts...';
  #     sleep 10;
  #     /usr/bin/mc config host add minio http://minio:9000 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY;
  #     /usr/bin/mc mb   minio/cwbi-data-develop   minio/cwbi-data-develop;
  #     /usr/bin/mc mb   minio/cwbi-data-stable   minio/cwbi-data-stable;
  #     /usr/bin/mc policy set public minio/cwbi-data-develop;
  #     /usr/bin/mc policy set public minio/cwbi-data-stable;
  #     /usr/bin/mc cp --recursive /media/ minio/cwbi-data-develop/cumulus/;
  #     /usr/bin/mc cp --recursive /media/ minio/cwbi-data-stable/cumulus/;
  #     exit 0;
  #     "
  #   volumes:
  #     - ./data:/media